//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dishes
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public string ProductID { get; set; }
        public string Article { get; set; }
        public int FabricID { get; set; }
        public int ProviderID { get; set; }
        public int OrderDetailID { get; set; }
        public int CategoryID { get; set; }
    
        public virtual Fabric Fabric { get; set; }
    }
}
