//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dishes
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tovar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tovar()
        {
            this.OrderDetail = new HashSet<OrderDetail>();
        }
    
        public string Article { get; set; }
        public string Name { get; set; }
        public string Ed { get; set; }
        public string Price { get; set; }
        public string MaxDiscount { get; set; }
        public int FabricID { get; set; }
        public int ProviderID { get; set; }
        public int CategoryID { get; set; }
        public string Deist { get; set; }
        public string Garage { get; set; }
        public string Details { get; set; }
        public string Img { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Fabric Fabric { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetail> OrderDetail { get; set; }
        public virtual Provider Provider { get; set; }
    }
}
